version: "3"

services: 
    al2:
        build: ./docker/al2
        environment:
            TZ: Asia/Tokyo
        tty: true
        privileged: true
        volumes:
            - ./html:/var/www/html
        ports:
            - 80:80
